name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build app
      run: |
        # Clean any existing build artifacts
        rm -rf build dist
        # Build the app in alias mode first for testing
        python setup.py py2app -A
        # If that succeeds, build the standalone app
        python setup.py py2app
        # Verify the app was created
        ls -la dist/
    
    - name: Create DMG
      run: |
        APP_PATH="dist/BitcoinPrice.app"
        if [ ! -d "$APP_PATH" ]; then
          echo "Looking for app in dist directory..."
          ls -la dist/
          # Try to find the app with a different name
          FOUND_APP=$(find dist -name "*.app" -maxdepth 1 -type d)
          if [ -n "$FOUND_APP" ]; then
            echo "Found app at: $FOUND_APP"
            mv "$FOUND_APP" "$APP_PATH"
          else
            echo "No .app bundle found in dist directory"
            exit 1
          fi
        fi
        
        mkdir -p dist/dmg
        cp -r "$APP_PATH" dist/dmg/
        hdiutil create -volname "Bitcoin Price" -srcfolder dist/dmg -ov -format UDZO dist/BitcoinPrice.dmg
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/BitcoinPrice.dmg
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
